Fix patient relationship primary key
EstebanOlmedo/melanoma-tt pull request #31
Opened 2023-11-10 15:39 UTC by EstebanOlmedo

This fixes the patient relationship model making both id's its primary key, as before there couldn't be more than one relationship with the same doctorId which isn't the expected behavior.

2023-11-11 00:55 UTC, DanielMontesGuerrero requested changes

2023-11-11 00:55 UTC, DanielMontesGuerrero commented on api/src/api/routes/user.ts
> +    log.error('Error while saving the relationship: ', error);
This must be log.error(error, message)

2023-11-11 19:03 UTC, brielgah commented on api/src/api/routes/user.ts
> +    log.error('Error while saving the relationship: ', error);
I will fix this error in my commit

2023-11-11 19:03 UTC, brielgah approved these changes
LGTM

2023-11-12 01:09 UTC, DanielMontesGuerrero approved these changes

2023-11-12 01:10 UTC, merged